runtime: python312
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "twomanspades"

beta_settings:
  cloud_sql_instances: "kumori-404602:us-central1:kumori"

handlers:
  - url: /static
    static_dir: static
    secure: always
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301